[project]
name = "vagrant-k8s-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible-dev-tools>=25.5.2",
    "ansible-lint>=25.6.1",
    "jmespath>=1.0.1",
]
